import { fetch } from '@tauri-apps/plugin-http';
import { sendOsc, OSC_ADDRESS } from './osc';
import { invoke } from '@tauri-apps/api/core';



async function getOpenAIToken() {
    return invoke('get_env',{name:'OPENAI_API_KEY'});
}

export async function sendChatMessage(messages, data) {

    const token = await getOpenAIToken();    
    const first_prompt = ([
        {
            role: "system",
            content: data.system_prompt
        }
    ]);
    

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
            model: 'gpt-4o',
            messages: [
                ...first_prompt,
                ...messages
            ],
            response_format: {
                type: 'json_schema',
                json_schema: {
                    name: "output_prompt",
                    description: "Output prompt schema for the model response",
                    schema:{
                        type: "object",
                        properties: {
                            "output_text": {
                                "type": "string",
                                "description": "The final output text generated by the model, without image prompt"
                            },
                            "prompt": {
                                "type": "string",
                                "description": "The generated image prompt based on the user's input and the system's guidance. Less than 60 English characters."
                            }
                        },
                        required: ["output_text", "prompt"],
                        additionalProperties: false
                    }
                }
            },
        }),
    });

    if (!response.ok) {
        const text= await response.text();
        console.error("Error response:", text);
        throw new Error(`HTTP error! status: ${response.status}`);        
    }
    const output= await response.json();
    const choice= output.choices[0];

    // console.log("Generated response:", choice.message);
    const result=JSON.parse(choice.message.content);    

    return {
        ...result,
        ok: true,
    };


}


export async function getSummary(messages, data) {

    const token = await getOpenAIToken();
    console.log("Generating summary for messages:", messages);

    const { summary_prompt } = data;
    
    

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
            model: 'gpt-4o',
            messages: [
                {
                    role: "system",
                    content:summary_prompt,
                },
                { 
                    role: "user", 
                    content: JSON.stringify(messages)
                },
            ],            
        }),
    });

    if (!response.ok) {
        const text= await response.text();
        console.error("Error response:", text);
        throw new Error(`HTTP error! status: ${response.status}`);        
    }
    const output= await response.json();
    const choice= output.choices[0];

    // console.log("Generated response:", choice.message);
    const result=choice.message.content;
    
    // send to tauri
    await sendOsc(OSC_ADDRESS.SUMMARY, result);


    return {
        result,
        ok: true,
    };


}
